In [78]:
import sys
sys.path.append(r'C:\Users\vanes\Git_repositories\HW3\HW3')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score
from scipy import stats
from sklearn.metrics import roc_auc_score
import HW3_library
from HW3_library.features.Data_loading import loaddata
from HW3_library.features.Data_cleaning import drop_na
from HW3_library.features.Data_cleaning import fill_na
from HW3_library.features.Data_cleaning import one_hot
from HW3_library.features.Data_cleaning import binary
from HW3_library.features.splitdata import splitdata
from HW3_library.features.model import model

In [67]:
df = loaddata(r'C:\Users\vanes\Git_repositories\HW3\sample_diabetes_mellitus_data.csv')

In [68]:
df = drop_na(df, ['age', 'gender', 'ethnicity'])
df

,Unnamed: 0,encounter_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,hospital_admit_source,...,ventilated_apache,wbc_apache,aids,cirrhosis,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,diabetes_mellitus
0,0,214826,118,68.0,22.732803,0,Caucasian,M,180.30,Floor,...,0,14.1,0,0,0,0,0,0,0,1
1,1,246060,81,77.0,27.421875,0,Caucasian,F,160.00,Floor,...,1,12.7,0,0,0,0,0,0,0,1
2,2,276985,118,25.0,31.952749,0,Caucasian,F,172.70,Emergency Department,...,0,NaN,0,0,0,0,0,0,0,0
3,3,262220,118,81.0,22.635548,1,Caucasian,F,165.10,Operating Room,...,1,8.0,0,0,0,0,0,0,0,0
4,4,201746,33,19.0,NaN,0,Caucasian,M,188.00,NaN,...,0,NaN,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,9994,271449,89,78.0,28.700475,0,Caucasian,F,172.70,Emergency Department,...,0,NaN,0,0,0,0,0,0,0,0
9996,9996,165009,89,34.0,26.110113,0,Caucasian,F,175.26,Emergency Department,...,0,9.5,0,0,0,0,0,0,0,0
9997,9997,234052,137,30.0,23.774241,0,Native American,F,157.48,Emergency Department,...,0,NaN,0,0,0,0,0,0,0,0
9998,9998,249290,89,67.0,31.330708,0,Caucasian,F,157.48,Direct Admit,...,0,6.4,0,0,0,0,0,0,0,0
9999,9999,151312,89,55.0,44.343663,0,Caucasian,F,157.50,Emergency Department,...,1,NaN,0,0,0,0,0,0,0,0

In [69]:
df = fill_na(df, ['height', 'weight'])
df.isna().sum()

Unnamed: 0                        0
encounter_id                      0
hospital_id                       0
age                               0
bmi                            1622
elective_surgery                  0
ethnicity                         0
gender                            0
height                            0
hospital_admit_source           850
icu_admit_source                 21
icu_id                            0
icu_stay_type                     0
icu_type                          0
pre_icu_los_days                  0
readmission_status                0
weight                            0
albumin_apache                 6046
apache_2_diagnosis              177
apache_3j_diagnosis              49
apache_post_operative             0
arf_apache                        0
bilirubin_apache               6170
bun_apache                     2372
creatinine_apache              2247
fio2_apache                    6583
gcs_eyes_apache                  65
gcs_motor_apache                 65
gcs_unable_apache                61
gcs_verbal_apache                65
glucose_apache                 1008
heart_rate_apache                 1
hematocrit_apache              1879
intubated_apache                  0
map_apache                       12
paco2_apache                   6583
paco2_for_ph_apache            6583
pao2_apache                    6583
ph_apache                      6583
resprate_apache                  33
sodium_apache                  2321
temp_apache                      85
urineoutput_apache             7981
ventilated_apache                 0
wbc_apache                     2054
aids                              0
cirrhosis                         0
hepatic_failure                   0
immunosuppression                 0
leukemia                          0
lymphoma                          0
solid_tumor_with_metastasis       0
diabetes_mellitus                 0
dtype: int64

In [70]:
df = one_hot(df, ['ethnicity'])
df

,Unnamed: 0,encounter_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,hospital_admit_source,...,leukemia,lymphoma,solid_tumor_with_metastasis,diabetes_mellitus,ethnicity_African American,ethnicity_Asian,ethnicity_Caucasian,ethnicity_Hispanic,ethnicity_Native American,ethnicity_Other/Unknown
0,0,214826,118,68.0,22.732803,0,Caucasian,M,180.30,Floor,...,0,0,0,1,False,False,True,False,False,False
1,1,246060,81,77.0,27.421875,0,Caucasian,F,160.00,Floor,...,0,0,0,1,False,False,True,False,False,False
2,2,276985,118,25.0,31.952749,0,Caucasian,F,172.70,Emergency Department,...,0,0,0,0,False,False,True,False,False,False
3,3,262220,118,81.0,22.635548,1,Caucasian,F,165.10,Operating Room,...,0,0,0,0,False,False,True,False,False,False
4,4,201746,33,19.0,NaN,0,Caucasian,M,188.00,NaN,...,0,0,0,0,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,9994,271449,89,78.0,28.700475,0,Caucasian,F,172.70,Emergency Department,...,0,0,0,0,False,False,True,False,False,False
9996,9996,165009,89,34.0,26.110113,0,Caucasian,F,175.26,Emergency Department,...,0,0,0,0,False,False,True,False,False,False
9997,9997,234052,137,30.0,23.774241,0,Native American,F,157.48,Emergency Department,...,0,0,0,0,False,False,False,False,True,False
9998,9998,249290,89,67.0,31.330708,0,Caucasian,F,157.48,Direct Admit,...,0,0,0,0,False,False,True,False,False,False
9999,9999,151312,89,55.0,44.343663,0,Caucasian,F,157.50,Emergency Department,...,0,0,0,0,False,False,True,False,False,False

In [71]:
df = binary(df, 'gender')
df

,Unnamed: 0,encounter_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,hospital_admit_source,...,lymphoma,solid_tumor_with_metastasis,diabetes_mellitus,ethnicity_African American,ethnicity_Asian,ethnicity_Caucasian,ethnicity_Hispanic,ethnicity_Native American,ethnicity_Other/Unknown,Binary
0,0,214826,118,68.0,22.732803,0,Caucasian,M,180.30,Floor,...,0,0,1,False,False,True,False,False,False,1
1,1,246060,81,77.0,27.421875,0,Caucasian,F,160.00,Floor,...,0,0,1,False,False,True,False,False,False,0
2,2,276985,118,25.0,31.952749,0,Caucasian,F,172.70,Emergency Department,...,0,0,0,False,False,True,False,False,False,0
3,3,262220,118,81.0,22.635548,1,Caucasian,F,165.10,Operating Room,...,0,0,0,False,False,True,False,False,False,0
4,4,201746,33,19.0,NaN,0,Caucasian,M,188.00,NaN,...,0,0,0,False,False,True,False,False,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,9994,271449,89,78.0,28.700475,0,Caucasian,F,172.70,Emergency Department,...,0,0,0,False,False,True,False,False,False,0
9996,9996,165009,89,34.0,26.110113,0,Caucasian,F,175.26,Emergency Department,...,0,0,0,False,False,True,False,False,False,0
9997,9997,234052,137,30.0,23.774241,0,Native American,F,157.48,Emergency Department,...,0,0,0,False,False,False,False,True,False,0
9998,9998,249290,89,67.0,31.330708,0,Caucasian,F,157.48,Direct Admit,...,0,0,0,False,False,True,False,False,False,0
9999,9999,151312,89,55.0,44.343663,0,Caucasian,F,157.50,Emergency Department,...,0,0,0,False,False,True,False,False,False,0

In [72]:
traindf, testdf = splitdata(df, 0.4, 42)
testdf

,Unnamed: 0,encounter_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,hospital_admit_source,...,lymphoma,solid_tumor_with_metastasis,diabetes_mellitus,ethnicity_African American,ethnicity_Asian,ethnicity_Caucasian,ethnicity_Hispanic,ethnicity_Native American,ethnicity_Other/Unknown,Binary
0,136,255681,118,64.0,35.951557,1,Caucasian,M,170.0,Operating Room,...,0,0,0,False,False,True,False,False,False,1
1,4882,271074,118,63.0,31.095278,0,Caucasian,M,182.0,Emergency Department,...,0,0,1,False,False,True,False,False,False,1
2,2313,252155,118,74.0,22.070312,1,Hispanic,M,160.0,Operating Room,...,0,0,0,False,False,False,True,False,False,1
3,1886,188562,118,65.0,NaN,0,Caucasian,M,180.3,Floor,...,0,0,0,False,False,True,False,False,False,1
4,3000,169616,77,77.0,28.343555,0,African American,M,175.3,Emergency Department,...,0,1,1,True,False,False,False,False,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3743,1941,162510,118,58.0,22.547294,1,Caucasian,F,154.9,Other Hospital,...,0,0,0,False,False,True,False,False,False,0
3744,7677,185062,118,47.0,NaN,0,African American,F,162.6,Floor,...,0,0,0,True,False,False,False,False,False,0
3745,1931,209662,31,87.0,22.321301,1,Caucasian,F,167.6,Operating Room,...,0,0,0,False,False,True,False,False,False,0
3746,7731,213279,83,32.0,31.478049,0,Caucasian,M,185.4,Direct Admit,...,0,0,0,False,False,True,False,False,False,1
3747,8816,266670,150,84.0,23.637658,0,Native American,M,172.7,Emergency Department,...,0,0,0,False,False,False,False,True,False,1

In [82]:
features = ['age', 'height', 'weight', 'aids', 'cirrhosis', 'hepatic_failure', 'immunosuppression', 'leukemia', 'lymphoma', 'solid_tumor_with_metastasis']
target = 'diabetes_mellitus'
model(traindf, testdf, features, target)

Train Accuracy: 0.9857651245551602
Test Accuracy: 0.7331910352187834
Train ROC AUC: 0.9988699082809489
Test ROC AUC: 0.6080131378752385

(      Unnamed: 0  encounter_id  hospital_id   age        bmi  \
 0           1969        206755          118  59.0  31.148727
 1           4581        147833           77  44.0        NaN
 2           4650        198256           83  73.0  19.975102
 3           9704        196242           89  84.0        NaN
 4           3877        266554           33  82.0  30.046537
 ...          ...           ...          ...   ...        ...
 5615        6062        201939          118  59.0        NaN
 5616        5494        227860           31  67.0  18.301839
 5617        5703        190499          118  85.0  18.296026
 5618         913        165385          118  43.0  23.661272
 5619        7681        242945          118  23.0  22.496401

       elective_surgery  ethnicity gender      height hospital_admit_source  \
 0                    1  Caucasian      M  182.900000                   NaN
 1                    0  Caucasian      M  188.000000          Direct Admit
 2                    0  Caucasian      M  188.000000        Other Hospital
 3                    0  Caucasian      M  170.137378        Operating Room
 4                    0  Caucasian      M  167.600000                 Floor
 ...                ...        ...    ...         ...                   ...
 5615                 1  Caucasian      M  167.600000        Operating Room
 5616                 0  Caucasian      F  157.500000                 Floor
 5617                 1  Caucasian      M  170.200000        Operating Room
 5618                 1  Caucasian      M  177.800000  Emergency Department
 5619                 0  Caucasian      M  190.500000  Emergency Department

       ... solid_tumor_with_metastasis  diabetes_mellitus  \
 0     ...                           0                  0
 1     ...                           0                  0
 2     ...                           0                  0
 3     ...                           0                  0
 4     ...                           0                  0
 ...   ...                         ...                ...
 5615  ...                           0                  0
 5616  ...                           0                  0
 5617  ...                           0                  0
 5618  ...                           0                  0
 5619  ...                           0                  0

      ethnicity_African American ethnicity_Asian  ethnicity_Caucasian  \
 0                         False           False                 True
 1                         False           False                 True
 2                         False           False                 True
 3                         False           False                 True
 4                         False           False                 True
 ...                         ...             ...                  ...
 5615                      False           False                 True
 5616                      False           False                 True
 5617                      False           False                 True
 5618                      False           False                 True
 5619                      False           False                 True

       ethnicity_Hispanic  ethnicity_Native American  ethnicity_Other/Unknown  \
 0                  False                      False                    False
 1                  False                      False                    False
 2                  False                      False                    False
 3                  False                      False                    False
 4                  False                      False                    False
 ...                  ...                        ...                      ...
 5615               False                      False                    False
 5616               False                      False                    False
 5617               False                      False                    False
 5618               False                      False                    False
 5619               False                      False                    False

       Binary  train_predictions
 0          1           0.080000
 1          1           0.020000
 2          1           0.080000
 3          1           0.198333
 4          1           0.220000
 ...      ...                ...
 5615       1           0.237500
 5616       0           0.050000
 5617       1           0.100000
 5618       1           0.010000
 5619       1           0.000000

 [5620 rows x 61 columns],
       Unnamed: 0  encounter_id  hospital_id   age        bmi  \
 0            136        255681          118  64.0  35.951557
 1           4882        271074          118  63.0  31.095278
 2           2313        252155          118  74.0  22.070312
 3           1886        188562          118  65.0        NaN
 4           3000        169616           77  77.0  28.343555
 ...          ...           ...          ...   ...        ...
 3743        1941        162510          118  58.0  22.547294
 3744        7677        185062          118  47.0        NaN
 3745        1931        209662           31  87.0  22.321301
 3746        7731        213279           83  32.0  31.478049
 3747        8816        266670          150  84.0  23.637658

       elective_surgery         ethnicity gender  height hospital_admit_source  \
 0                    1         Caucasian      M   170.0        Operating Room
 1                    0         Caucasian      M   182.0  Emergency Department
 2                    1          Hispanic      M   160.0        Operating Room
 3                    0         Caucasian      M   180.3                 Floor
 4                    0  African American      M   175.3  Emergency Department
 ...                ...               ...    ...     ...                   ...
 3743                 1         Caucasian      F   154.9        Other Hospital
 3744                 0  African American      F   162.6                 Floor
 3745                 1         Caucasian      F   167.6        Operating Room
 3746                 0         Caucasian      M   185.4          Direct Admit
 3747                 0   Native American      M   172.7  Emergency Department

       ... solid_tumor_with_metastasis  diabetes_mellitus  \
 0     ...                           0                  0
 1     ...                           0                  1
 2     ...                           0                  0
 3     ...                           0                  0
 4     ...                           1                  1
 ...   ...                         ...                ...
 3743  ...                           0                  0
 3744  ...                           0                  0
 3745  ...                           0                  0
 3746  ...                           0                  0
 3747  ...                           0                  0

      ethnicity_African American ethnicity_Asian  ethnicity_Caucasian  \
 0                         False           False                 True
 1                         False           False                 True
 2                         False           False                False
 3                         False           False                 True
 4                          True           False                False
 ...                         ...             ...                  ...
 3743                      False           False                 True
 3744                       True           False                False
 3745                      False           False                 True
 3746                      False           False                 True
 3747                      False           False                False

       ethnicity_Hispanic  ethnicity_Native American  ethnicity_Other/Unknown  \
 0                  False                      False                    False
 1                  False                      False                    False
 2                   True                      False                    False
 3                  False                      False                    False
 4                  False                      False                    False
 ...                  ...                        ...                      ...
 3743               False                      False                    False
 3744               False                      False                    False
 3745               False                      False                    False
 3746               False                      False                    False
 3747               False                       True                    False

       Binary  test_predictions
 0          1          0.200000
 1          1          0.290000
 2          1          0.150000
 3          1          0.031667
 4          1          0.500000
 ...      ...               ...
 3743       0          0.140000
 3744       0          0.080000
 3745       0          0.150000
 3746       1          0.060000
 3747       1          0.130000

 [3748 rows x 61 columns])